# Generated by Django 3.0.6 on 2020-05-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='Email',
            field=models.EmailField(max_length=200),
            preserve_default=False,
        ),
    ]
