# Generated by Django 3.0.6 on 2020-05-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0002_studentdetails_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=200)),
                ('Last_name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('Registration_date', models.DateField()),
                ('About_website', models.TextField()),
                ('User_role', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentDetails',
        ),
    ]
