# Generated by Django 3.0.6 on 2020-05-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0003_auto_20200512_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Date', models.CharField(max_length=200)),
                ('Time', models.CharField(max_length=200)),
            ],
        ),
    ]
