# Generated by Django 3.0.6 on 2020-05-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0004_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('From_email', models.EmailField(max_length=254)),
                ('To_email', models.EmailField(max_length=254)),
                ('Message_content', models.TextField(default='Nil')),
            ],
        ),
    ]
