# Generated by Django 3.0.6 on 2020-05-18 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0006_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
