# Generated by Django 3.0.6 on 2020-05-18 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0007_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=200)),
                ('Student_email', models.EmailField(max_length=254)),
                ('Course_name', models.CharField(max_length=200)),
                ('Feedback_text', models.TextField(default='Nil')),
                ('Submission_date', models.DateField()),
                ('Feed_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face.Registration')),
            ],
        ),
    ]
