# Generated by Django 3.0.6 on 2020-05-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0010_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Blog_content', models.TextField()),
                ('Image', models.ImageField(upload_to='')),
                ('Date_blog', models.DateField()),
                ('Approval_status', models.CharField(max_length=200)),
            ],
        ),
    ]
