# Generated by Django 3.0.6 on 2020-05-19 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0011_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=200)),
                ('Student_email', models.EmailField(max_length=254)),
                ('Teacher_name', models.CharField(max_length=200)),
                ('Subject_name', models.CharField(max_length=200)),
                ('Course_name', models.CharField(max_length=200)),
                ('Question', models.TextField()),
                ('Option1', models.TextField()),
                ('Option2', models.TextField()),
                ('Option3', models.TextField()),
                ('Correct_answer', models.TextField()),
                ('Lock', models.CharField(max_length=200)),
                ('Time_start', models.DateTimeField()),
                ('Time_stop', models.DateTimeField()),
                ('Exam_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face.Registration')),
            ],
        ),
    ]
