# Generated by Django 3.0.6 on 2020-05-20 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0012_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='Course_name',
        ),
        migrations.CreateModel(
            name='Exam_results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=200)),
                ('Student_email', models.EmailField(max_length=200)),
                ('Teacher_name', models.CharField(max_length=200)),
                ('Teacher_email', models.EmailField(max_length=254)),
                ('Subject_name', models.CharField(max_length=200)),
                ('Total_marks', models.IntegerField()),
                ('Acquired_marks', models.IntegerField()),
                ('Grade', models.CharField(max_length=200)),
                ('Time_stop', models.DateTimeField(auto_now=True)),
                ('Exam_res_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face.Registration')),
            ],
        ),
    ]
