# Generated by Django 3.0.6 on 2020-05-20 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0013_auto_20200520_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Cou_reg',
        ),
    ]
