# Generated by Django 3.0.6 on 2020-05-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0016_auto_20200522_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='Parent_phone',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
    ]
