# Generated by Django 3.0.6 on 2020-05-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0017_registration_parent_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Teacher_email',
            field=models.EmailField(max_length=254),
            preserve_default=False,
        ),
    ]
