# Generated by Django 3.0.6 on 2020-05-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0018_feedback_teacher_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='Class',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='Course',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='Semester',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
