# Generated by Django 3.0.6 on 2020-05-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0020_auto_20200523_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Class',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Semester',
            field=models.IntegerField(null=True),
        ),
    ]
